import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "../contexts/ThemeContext";
import { SessionProviderWrapper } from "../contexts/SessionContext";
import { NextAuthProvider } from "../components/providers/NextAuthProvider";
import { FlashCardProvider } from "../contexts/FlashCardContext";
import { SpeedInsights } from "@vercel/speed-insights/next"

// Remove unused import if not needed

export const metadata: Metadata = {
  title: "Ace It AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`antialiased`}
      >
          <ThemeProvider>
            <SessionProviderWrapper>
              <NextAuthProvider>
                <FlashCardProvider>
                  {children}
                  <SpeedInsights />
                </FlashCardProvider>
              </NextAuthProvider>
            </SessionProviderWrapper>
          </ThemeProvider>
      </body>
    </html>
  );
}
