import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/contexts/ThemeContext";
import { SessionProviderWrapper } from "@/contexts/SessionContext";
import { NextAuthProvider } from "@/components/providers/NextAuthProvider";
import { FlashCardProvider } from "@/contexts/FlashCardContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ace It AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <ThemeProvider>
            <SessionProviderWrapper>
              <NextAuthProvider>
                <FlashCardProvider>
                  {children}
                </FlashCardProvider>
              </NextAuthProvider>
            </SessionProviderWrapper>
          </ThemeProvider>
      </body>
    </html>
  );
}
