import type { Metadata } from "next";
import "./globals.css";
import "react-loading-skeleton/dist/skeleton.css";
import { ThemeProvider } from "../contexts/ThemeContext";
import { SessionProviderWrapper } from "../contexts/SessionContext";
import { NextAuthProvider } from "../components/providers/NextAuthProvider";
import { FlashCardProvider } from "../contexts/FlashCardContext";
import { GuestProvider } from "../contexts/GuestContext";
import { SpeedInsights } from "@vercel/speed-insights/next"

export const metadata: Metadata = {
  title: "Ace It AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`antialiased`}
      >
          <ThemeProvider>
            <SessionProviderWrapper>
              <NextAuthProvider>
                <GuestProvider>
                  <FlashCardProvider>
                    {children}
                    <SpeedInsights />
                  </FlashCardProvider>
                </GuestProvider>
              </NextAuthProvider>
            </SessionProviderWrapper>
          </ThemeProvider>
      </body>
    </html>
  );
}
