"use client"

import React from 'react';
import AppBar from '@/components/AppBar';
import Footer from '@/components/Footer';

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen transition-colors duration-500 bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900">
      {/* Subtle background pattern */}
      <div className="fixed inset-0 opacity-5">
        <div className="absolute inset-0 bg-gradient-to-r from-blue-500/10 to-teal-500/10"></div>
        <div className="absolute top-0 left-1/3 w-72 h-72 sm:w-96 sm:h-96 bg-blue-500/5 rounded-full blur-3xl"></div>
        <div className="absolute bottom-0 right-1/3 w-72 h-72 sm:w-96 sm:h-96 bg-teal-500/5 rounded-full blur-3xl"></div>
      </div>

      <div className="relative z-10">
        {/* Navigation */}
        <AppBar />

        {/* Privacy Policy Content */}
        <div className="max-w-4xl mx-auto px-4 sm:px-6 py-12 sm:py-16 lg:py-24">
          <div className="mb-12 sm:mb-16">
            <h1 className="text-3xl sm:text-4xl lg:text-5xl font-bold mb-4 sm:mb-6 bg-gradient-to-r from-blue-600 via-teal-600 to-cyan-600 bg-clip-text text-transparent tracking-tight">
              PRIVACY POLICY
            </h1>
            <p className="text-lg sm:text-xl text-slate-300 font-light">Last updated June 13, 2025</p>
          </div>

          <div className="space-y-8 sm:space-y-12">
            {/* Introduction */}
            <section className="p-6 sm:p-8 rounded-2xl bg-slate-800/50 border border-slate-700/50 backdrop-blur-md shadow-xl">
              <h2 className="text-2xl sm:text-3xl font-bold text-white mb-6">INTRODUCTION</h2>
              <div className="space-y-4 text-base sm:text-lg font-light text-slate-300 leading-relaxed">
                <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
                
                <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
              </div>
            </section>

            {/* Interpretation and Definitions */}
            <section className="p-6 sm:p-8 rounded-2xl bg-slate-800/50 border border-slate-700/50 backdrop-blur-md shadow-xl">
              <h2 className="text-2xl sm:text-3xl font-bold text-white mb-6">INTERPRETATION AND DEFINITIONS</h2>
              
              <div className="space-y-6">
                <div>
                  <h3 className="text-xl font-bold text-white mb-3">Interpretation</h3>
                  <p className="text-base sm:text-lg font-light text-slate-300 leading-relaxed">
                    The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                  </p>
                </div>

                <div>
                  <h3 className="text-xl font-bold text-white mb-3">Definitions</h3>
                  <div className="space-y-3 text-base sm:text-lg font-light text-slate-300 leading-relaxed">
                    <p>For the purposes of this Privacy Policy:</p>
                    <ul className="list-disc pl-6 space-y-2">
                      <li><strong className="text-white">Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                      <li><strong className="text-white">Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Ace It AI.</li>
                      <li><strong className="text-white">Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                      <li><strong className="text-white">Country</strong> refers to: Andhra Pradesh, India</li>
                      <li><strong className="text-white">Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                      <li><strong className="text-white">Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                      <li><strong className="text-white">Service</strong> refers to the Website.</li>
                      <li><strong className="text-white">Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
                      <li><strong className="text-white">Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
                      <li><strong className="text-white">Website</strong> refers to Ace It AI, accessible from https://ace-it-ai-wine.vercel.app/</li>
                      <li><strong className="text-white">You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                    </ul>
                  </div>
                </div>
              </div>
            </section>

            {/* Collecting and Using Your Personal Data */}
            <section className="p-6 sm:p-8 rounded-2xl bg-slate-800/50 border border-slate-700/50 backdrop-blur-md shadow-xl">
              <h2 className="text-2xl sm:text-3xl font-bold text-white mb-6">COLLECTING AND USING YOUR PERSONAL DATA</h2>
              
              <div className="space-y-6">
                <div>
                  <h3 className="text-xl font-bold text-white mb-3">Types of Data Collected</h3>
                  
                  <div className="space-y-4">
                    <div>
                      <h4 className="text-lg font-semibold text-white mb-2">Personal Data</h4>
                      <div className="space-y-3 text-base sm:text-lg font-light text-slate-300 leading-relaxed">
                        <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                        <ul className="list-disc pl-6 space-y-1">
                          <li>Email address</li>
                          <li>First name and last name</li>
                          <li>Usage Data</li>
                        </ul>
                      </div>
                    </div>

                    <div>
                      <h4 className="text-lg font-semibold text-white mb-2">Usage Data</h4>
                      <div className="space-y-3 text-base sm:text-lg font-light text-slate-300 leading-relaxed">
                        <p>Usage Data is collected automatically when using the Service.</p>
                        <p>Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                        <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
                      </div>
                    </div>

                    <div>
                      <h4 className="text-lg font-semibold text-white mb-2">Tracking Technologies and Cookies</h4>
                      <div className="space-y-3 text-base sm:text-lg font-light text-slate-300 leading-relaxed">
                        <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. The technologies We use may include:</p>
                        <ul className="list-disc pl-6 space-y-2">
                          <li><strong className="text-white">Cookies or Browser Cookies:</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent.</li>
                          <li><strong className="text-white">Web Beacons:</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons that permit the Company to count users who have visited those pages.</li>
                        </ul>
                        <p>We use both Session and Persistent Cookies for the following purposes:</p>
                        <ul className="list-disc pl-6 space-y-2">
                          <li><strong className="text-white">Necessary / Essential Cookies:</strong> These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features.</li>
                          <li><strong className="text-white">Cookies Policy / Notice Acceptance Cookies:</strong> These Cookies identify if users have accepted the use of cookies on the Website.</li>
                          <li><strong className="text-white">Functionality Cookies:</strong> These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference.</li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>

                <div>
                  <h3 className="text-xl font-bold text-white mb-3">Use of Your Personal Data</h3>
                  <div className="space-y-3 text-base sm:text-lg font-light text-slate-300 leading-relaxed">
                    <p>The Company may use Personal Data for the following purposes:</p>
                    <ul className="list-disc pl-6 space-y-2">
                      <li><strong className="text-white">To provide and maintain our Service:</strong> including to monitor the usage of our Service.</li>
                      <li><strong className="text-white">To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
                      <li><strong className="text-white">For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased.</li>
                      <li><strong className="text-white">To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
                      <li><strong className="text-white">To provide You with news and offers:</strong> about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about.</li>
                      <li><strong className="text-white">To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
                      <li><strong className="text-white">For business transfers:</strong> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
                      <li><strong className="text-white">For other purposes:</strong> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns.</li>
                    </ul>
                  </div>
                </div>

                <div>
                  <h3 className="text-xl font-bold text-white mb-3">Retention of Your Personal Data</h3>
                  <p className="text-base sm:text-lg font-light text-slate-300 leading-relaxed">
                    The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
                  </p>
                </div>

                <div>
                  <h3 className="text-xl font-bold text-white mb-3">Transfer of Your Personal Data</h3>
                  <div className="space-y-3 text-base sm:text-lg font-light text-slate-300 leading-relaxed">
                    <p>Your information, including Personal Data, is processed at the Company&apos;s operating offices and in any other places where the parties involved in the processing are located.</p>
                    <p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
                    <p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy.</p>
                  </div>
                </div>

                <div>
                  <h3 className="text-xl font-bold text-white mb-3">Delete Your Personal Data</h3>
                  <div className="space-y-3 text-base sm:text-lg font-light text-slate-300 leading-relaxed">
                    <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>
                    <p>Our Service may give You the ability to delete certain information about You from within the Service.</p>
                    <p>You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section.</p>
                  </div>
                </div>

                <div>
                  <h3 className="text-xl font-bold text-white mb-3">Security of Your Personal Data</h3>
                  <p className="text-base sm:text-lg font-light text-slate-300 leading-relaxed">
                    The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
                  </p>
                </div>
              </div>
            </section>

            {/* Children's Privacy */}
            <section className="p-6 sm:p-8 rounded-2xl bg-slate-800/50 border border-slate-700/50 backdrop-blur-md shadow-xl">
              <h2 className="text-2xl sm:text-3xl font-bold text-white mb-6">CHILDREN&apos;S PRIVACY</h2>
              <div className="space-y-4 text-base sm:text-lg font-light text-slate-300 leading-relaxed">
                <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13.</p>
                <p>If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
                <p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent&apos;s consent before We collect and use that information.</p>
              </div>
            </section>

            {/* Links to Other Websites */}
            <section className="p-6 sm:p-8 rounded-2xl bg-slate-800/50 border border-slate-700/50 backdrop-blur-md shadow-xl">
              <h2 className="text-2xl sm:text-3xl font-bold text-white mb-6">LINKS TO OTHER WEBSITES</h2>
              <div className="space-y-4 text-base sm:text-lg font-light text-slate-300 leading-relaxed">
                <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party&apos;s site.</p>
                <p>We strongly advise You to review the Privacy Policy of every site You visit.</p>
                <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
              </div>
            </section>

            {/* Changes to Privacy Policy */}
            <section className="p-6 sm:p-8 rounded-2xl bg-slate-800/50 border border-slate-700/50 backdrop-blur-md shadow-xl">
              <h2 className="text-2xl sm:text-3xl font-bold text-white mb-6">CHANGES TO THIS PRIVACY POLICY</h2>
              <div className="space-y-4 text-base sm:text-lg font-light text-slate-300 leading-relaxed">
                <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
                <p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.</p>
                <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
              </div>
            </section>

            {/* Contact Us */}
            <section className="p-6 sm:p-8 rounded-2xl bg-gradient-to-r from-slate-800/70 to-slate-700/70 border border-slate-600/50 backdrop-blur-md shadow-xl">
              <h2 className="text-2xl sm:text-3xl font-bold text-white mb-6">CONTACT US</h2>
              <div className="space-y-4 text-base sm:text-lg font-light text-slate-300 leading-relaxed">
                <p>If you have any questions about this Privacy Policy, You can contact us:</p>
                
                <div className="p-4 rounded-xl bg-slate-800/50 border border-slate-700/50">
                  <p className="text-white font-medium">
                    Ace It AI<br />
                    By email: amaantheone@gmail.com
                  </p>
                </div>
              </div>
            </section>
          </div>
        </div>

        {/* Footer */}
        <Footer />
      </div>
    </div>
  );
}